@startuml
skinparam actorStyle awesome

actor Worker
usecase "Recharge myself after work at home" as JobStatement
usecase "...
-- Functional Outcome --" as FunctionalOutcome
' usecase "...
' -- Emotional Outcome --" as EmotionalOutcome


' Worker --> JobStatement
' FunctionalOutcome --> JobStatement
' EmotionalOutcome --> JobStatement

@endumle