@startuml
skinparam actorStyle awesome

actor Worker
usecase "Recharge after work at home" as JobStatement
usecase "...\n-- Functional Outcome --" as FunctionalOutcome
usecase "...\n-- Emotional Outcome --" as EmotionalOutcome


Worker --> JobStatement
FunctionalOutcome -u-> JobStatement
EmotionalOutcome -u-> JobStatement

@endumle